CREATE TABLE STAGE_TIMES (
   STAGE_NAME VARCHAR(255) NOT NULL,
   ARTIST_NAME VARCHAR(255) NOT NULL,
   SET_TIME VARCHAR(255) NOT NULL,
   DAY VARCHAR(40) NOT NULL,
   PRIMARY KEY (STAGE_NAME, ARTIST_NAME, SET_TIME, DAY)
);

CREATE TABLE USERS (
   USER_ID INT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(255) NOT NULL,
   NICKNAME VARCHAR(255) NOT NULL,
   DATE_OF_BIRTH DATE NOT NULL,
   LOCATION VARCHAR(255) NOT NULL,
   PRIMARY KEY (USER_ID)
);

CREATE TABLE USER_SCHEDULES (
   USER_ID INT NOT NULL AUTO_INCREMENT,
   STAGE_NAME VARCHAR(255) NOT NULL,
   ARTIST_NAME VARCHAR(255) NOT NULL,
   SET_TIME VARCHAR(255) NOT NULL,
   DAY VARCHAR(40) NOT NULL,
   PRIMARY KEY (USER_ID,STAGE_NAME, ARTIST_NAME, SET_TIME, DAY)
);
