-- STAGE_TIMES INSERTS
INSERT INTO `STAGE_TIMES`(`STAGE_NAME`, `ARTIST_NAME`, `SET_TIME`, `DAY`) VALUES ('Main','Bonobo','12:00-13:00','Saturday');
INSERT INTO `STAGE_TIMES`(`STAGE_NAME`, `ARTIST_NAME`, `SET_TIME`, `DAY`) VALUES ('Selectors','MCDE','14:00-15:00','Saturday');
INSERT INTO `STAGE_TIMES`(`STAGE_NAME`, `ARTIST_NAME`, `SET_TIME`, `DAY`) VALUES ('Boiler Room','Ben Klock','16:00-17:00','Sunday');
INSERT INTO `STAGE_TIMES`(`STAGE_NAME`, `ARTIST_NAME`, `SET_TIME`, `DAY`) VALUES ('Greenhouse','Moodymann','22:00-23:30','Sunday');
INSERT INTO `STAGE_TIMES`(`STAGE_NAME`, `ARTIST_NAME`, `SET_TIME`, `DAY`) VALUES ('Main','DJ Koze','15:00-16:00','Friday');